version: '3'

services:
  postgres_db:
    container_name: postgres_database
    image: postgres
    volumes:
      - postgres_volume:/data/postgres/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    restart: always
    networks:
      - app_ruby-db_postgres
  
  ruby_app:
    container_name: ruby_application
    build: .
    ports:
      - "3000:3000"
    networks:
      - app_ruby-db_postgres
    volumes:
      - .:/data/app/
    depends_on:
      - postgres_db

  nginx:
    container_name: nginx_server
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ruby_app
    networks:
      - app_ruby-db_postgres

networks:
  app_ruby-db_postgres:
    driver: bridge

volumes:
  postgres_volume:
    driver: local