name: Continuous Deployment to Docker Hub

on:
  push:
    branches: [main]

jobs:
  github-ci: 
    uses: nicaloribeiro/Trabalho-Individual-2021-2/.github/workflows/github-ci.yml@main
  deploy:
    needs: [github-ci]
    name: Continuous Deployment

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up docker build
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest