name: GitHub CI
on: 
  push:
    branches: [ main ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Docker Network
        working-directory: ./aplicacao
        run: docker network create app_ruby-db_postgres

      - name: Build Docker image
        working-directory: ./aplicacao
        run: docker-compose up -d
  
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Docker Network
        working-directory: ./aplicacao
        run: docker network create app_ruby-db_postgres

      - name: Run Tests
        working-directory: ./aplicacao
        run: docker-compose run ruby_app bash -c "rails db:reset; rspec"

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Docker Network
        working-directory: ./aplicacao
        run: docker network create app_ruby-db_postgres
      
      - name: Run Lint
        working-directory: ./aplicacao
        run: docker-compose run ruby_app bash -c "gem install rubocop; rubocop -A --fail-level F"
